### ISSUE TITLE
wxGCDC(cg)::SetTextBackground - invalid DC

### ISSUE THREAD

**Issue by andreagavazzi** [vanadiumlabs/arbotix_ros#49]
On plain ROS-Melodic (Ubuntu 18.04) when executing

`rosrun arbotix_python arbotix_gui` 

We get the following error

[INFO] [1617740796.278069]: No URDF defined, proceeding with defaults
Traceback (most recent call last):
  File "/home/andrea/catkin_ws/src/arbotix_ros/arbotix_python/bin/arbotix_gui", line 205, in <module>
    frame = controllerGUI(None, True)
  File "/home/andrea/catkin_ws/src/arbotix_ros/arbotix_python/bin/arbotix_gui", line 131, in __init__
    self.onPaint()
  File "/home/andrea/catkin_ws/src/arbotix_ros/arbotix_python/bin/arbotix_gui", line 160, in onPaint
    dc = wx.PaintDC(self.movebase)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk3/wx/_gdi.py", line 5130, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "IsOk()" failed at ../src/common/dcgraph.cpp(437) in SetTextBackground(): wxGCDC(cg)::SetTextBackground - invalid DC

**Comment by mikeferguson** [comment]
Archiving shortly
